### PR TITLE
Ref[Tracker][53134][Admin del change showtimes] 

### PR DESCRIPTION
**Pull request by congth2001**
## Related Tickets
- [#53134](https://edu-redmine.sun-asterisk.vn/issues/53134)

## WHAT (optional)
- Admin can change information or delete showtimes for movies

## HOW
- Using resources (update, edit, delete) to routes pages for change and delete showtimes

### CODE REVIEW

**Comment by congth2001** [comment]
ready

**Review by ghost — COMMENTED** [review]
Sửa xóa ntn thì có ảnh hưởng gì đến vé đã đặt ko em

**Comment by congth2001** [comment]
ready

**Review by ghost — COMMENTED** [review]
merged

**Pull request merged**
